import { Component, OnInit } from "@angular/core";
import { GalleryItem, ImageItem } from "ng-gallery";

const images = [
  "https://i.ibb.co/Tr38XRJ/1.jpg",
  "https://i.ibb.co/wzHXM2V/2.jpg",
  "https://i.ibb.co/HtVbmPQ/3.jpg",
  "https://i.ibb.co/p4CyV9s/4.jpg",
  "https://i.ibb.co/PNwc4gL/5.jpg",
  "https://i.ibb.co/Ssb7Db8/6.jpg",
  "https://i.ibb.co/T0s2BkH/7.jpg",
  "https://i.ibb.co/vs082nD/8.jpg",
  "https://i.ibb.co/rwmC1vt/9.jpg",
  "https://i.ibb.co/GnDND00/10.jpg",
  "https://i.ibb.co/jJG29yS/11.jpg",
  "https://i.ibb.co/x7ymRW8/12.jpg",
  "https://i.ibb.co/f27n8Rj/13.jpg",
  "https://i.ibb.co/PWrJ02S/14.jpg",
  "https://i.ibb.co/2K1fx5m/15.jpg",
  "https://i.ibb.co/LJYFZ8k/16.jpg",
  "https://i.ibb.co/jbDHcLm/17.jpg",
  "https://i.ibb.co/h2NQ8zC/18.jpg",
  "https://i.ibb.co/G3hKgTK/19.jpg",
  "https://i.ibb.co/2Wn4YrS/20.jpg",
  "https://i.ibb.co/DtRKwqP/21.jpg",
  "https://i.ibb.co/pLHdDVP/22.jpg",
  "https://i.ibb.co/fMzdtQ7/23.jpg",
  "https://i.ibb.co/gTgckTp/24.jpg",
  "https://i.ibb.co/6rDzXyz/25.jpg",
  "https://i.ibb.co/Stg6nYJ/26.jpg",
  "https://i.ibb.co/yy8k4LY/27.jpg",
  "https://i.ibb.co/gWNQMJg/28.jpg",
  "https://i.ibb.co/QC2N8nN/29.jpg",
  "https://i.ibb.co/n0r1DFt/30.jpg",
  "https://i.ibb.co/YNfXk07/31.jpg",
  "https://i.ibb.co/hFKHShD/32.jpg",
  "https://i.ibb.co/ZV6Tzty/33.jpg",
  "https://i.ibb.co/wRkX3qf/34.jpg",
  "https://i.ibb.co/MGyDRX0/35.jpg",
  "https://i.ibb.co/MPcWHk7/36.jpg",
  "https://i.ibb.co/d59BQfr/37.jpg",
  "https://i.ibb.co/X7FjVrJ/38.jpg",
  "https://i.ibb.co/Q91WMqF/39.jpg",
  "https://i.ibb.co/NKqmMqF/40.jpg",
  "https://i.ibb.co/3MXtRY1/41.jpg",
  "https://i.ibb.co/wMfCYB1/42.jpg",
  "https://i.ibb.co/2h3SfWz/43.jpg",
  "https://i.ibb.co/BV4WK89/44.jpg",
  "https://i.ibb.co/3fTQdTJ/45.jpg",
  "https://i.ibb.co/r4Ff0KL/46.jpg",
  "https://i.ibb.co/GkVrpkZ/47.jpg",
  "https://i.ibb.co/C16QZWr/48.jpg",
  "https://i.ibb.co/Q61JLrY/49.jpg",
  "https://i.ibb.co/bbFvW8j/50.jpg",
  "https://i.ibb.co/cY49qhR/51.jpg",
  "https://i.ibb.co/Ltnt3Gn/52.jpg",
  "https://i.ibb.co/YLT5bgD/53.jpg",
  "https://i.ibb.co/Ry3RdBj/54.jpg",
  "https://i.ibb.co/CW300TR/55.jpg",
  "https://i.ibb.co/Qv3nJdJ/56.jpg",
  "https://i.ibb.co/s6nKXCH/57.jpg",
  "https://i.ibb.co/fnhmtpf/58.jpg",
  "https://i.ibb.co/QbGq0jB/59.jpg",
  "https://i.ibb.co/ccjHd1f/60.jpg",
  "https://i.ibb.co/q95Dhgg/61.jpg",
  "https://i.ibb.co/n3yTzX9/62.jpg",
  "https://i.ibb.co/3pFVz24/63.jpg",
  "https://i.ibb.co/SvDmRkW/64.jpg",
  "https://i.ibb.co/mT3rdwm/65.jpg",
  "https://i.ibb.co/dMPZpsx/66.jpg",
  "https://i.ibb.co/XYjBVhC/67.jpg",
  "https://i.ibb.co/bH7X1BP/68.jpg",
  "https://i.ibb.co/PzzhzHz/69.jpg",
  "https://i.ibb.co/nLCjXhT/70.jpg",
  "https://i.ibb.co/FWN09FN/71.jpg",
  "https://i.ibb.co/mcNTwHc/72.jpg",
  "https://i.ibb.co/G0WJJS5/73.jpg",
  "https://i.ibb.co/3SVTyy1/74.jpg",
  "https://i.ibb.co/4dq5LMm/75.jpg",
  "https://i.ibb.co/JcyPL6t/76.jpg",
  "https://i.ibb.co/XF8zHN6/77.jpg",
  "https://i.ibb.co/3spNhB9/78.jpg",
  "https://i.ibb.co/qy4nVJh/79.jpg",
  "https://i.ibb.co/xJ85YkW/80.jpg",
  "https://i.ibb.co/qxcgNfY/81.jpg",
  "https://i.ibb.co/BtW5jWy/82.jpg",
  "https://i.ibb.co/7JFJCTB/83.jpg",
  "https://i.ibb.co/dmC8J1m/84.jpg",
  "https://i.ibb.co/BZpR0NC/85.jpg",
  "https://i.ibb.co/3R78xN9/86.jpg",
  "https://i.ibb.co/t4pBffv/87.jpg",
  "https://i.ibb.co/h1hk9T5/88.jpg",
  "https://i.ibb.co/wLnRVp3/89.jpg",
  "https://i.ibb.co/P5wzw8z/90.jpg",
  "https://i.ibb.co/Qjy4cXC/91.jpg",
  "https://i.ibb.co/Wk2sG1r/92.jpg",
  "https://i.ibb.co/HFFr9PQ/93.jpg",
  "https://i.ibb.co/MczKbj6/94.jpg",
  "https://i.ibb.co/8dbXR7w/95.jpg",
  "https://i.ibb.co/MVdhLQ3/96.jpg",
  "https://i.ibb.co/fd80SZj/97.jpg",
  "https://i.ibb.co/VqW5DMn/98.jpg",
  "https://i.ibb.co/mGnPFZ3/99.jpg",
  "https://i.ibb.co/HDTPWfd/100.jpg",
  "https://i.ibb.co/QbjFSB1/101.jpg",
  "https://i.ibb.co/5Wp8bK6/102.jpg",
  "https://i.ibb.co/h24tcKz/103.jpg",
  "https://i.ibb.co/BnP8hwq/104.jpg",
  "https://i.ibb.co/vwsgPL7/105.jpg",
  "https://i.ibb.co/9wSfB60/106.jpg",
  "https://i.ibb.co/16cQN4z/107.jpg",
  "https://i.ibb.co/6YD4PD5/108.jpg",
  "https://i.ibb.co/KGrb57C/109.jpg",
  "https://i.ibb.co/BBGCJYy/110.jpg",
  "https://i.ibb.co/FJbcPB6/111.jpg",
  "https://i.ibb.co/5Fqzj0s/112.jpg",
  "https://i.ibb.co/pPydPtR/113.jpg",
  "https://i.ibb.co/vwbdgJX/114.jpg",
  "https://i.ibb.co/hWWss4h/115.jpg",
  "https://i.ibb.co/0cGM4kN/116.jpg",
  "https://i.ibb.co/t2xWrPJ/117.jpg",
  "https://i.ibb.co/fv8bz5p/118.jpg",
  "https://i.ibb.co/yWwVPTW/119.jpg",
  "https://i.ibb.co/k25JrPd/120.jpg",
  "https://i.ibb.co/d70v745/121.jpg",
  "https://i.ibb.co/pjTSrx1/122.jpg",
  "https://i.ibb.co/09P7s4z/123.jpg",
  "https://i.ibb.co/4wbYYwQ/124.jpg",
  "https://i.ibb.co/NWDdzjK/125.jpg",
  "https://i.ibb.co/R2CYTWs/126.jpg",
  "https://i.ibb.co/LdmHTkS/127.jpg",
  "https://i.ibb.co/dfbmmNn/128.jpg",
  "https://i.ibb.co/4dY696v/129.jpg",
];

@Component({
  selector: "app-gallery",
  templateUrl: "./gallery.component.html",
  styleUrls: ["./gallery.component.css"],
})
export class GalleryComponent implements OnInit {
  public items: GalleryItem[];

  constructor() {
    // this.items = images.map((src) => new ImageItem({ src: src, thumb: src }));
    this.items = [new ImageItem({ src: images[0], thumb: images[0] })];
  }

  ngOnInit(): void {}
}
